In [25]:
#!pip install skrebate scikit-learn pandas numpy matplotlib seaborn

$\textbf{Step 0: Importing all necessary libraries}$

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import time
import pickle
warnings.filterwarnings('ignore')

#Importing The ReliefF Library to Implement for Phase 2
from skrebate import ReliefF

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import StratifiedKFold, GridSearchCV
from sklearn.metrics import accuracy_score, f1_score

#Importing Libraries for the 5 Classifiers that will be used
from sklearn.svm import LinearSVC, SVC
from sklearn.calibration import CalibratedClassifierCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier

$\textbf{Step 1: Loading Datasets and Setting the Parameters for Models and}$
$\textbf{ReliefF Algorithm}$

In [27]:
DATASETS = {
    'Dataset1' : {'train': 'Datasets/1/train.csv','test': None},
    'Dataset2' : {'train': 'Datasets/2/train.csv','test': None},
    'Dataset3' : {'train': 'Datasets/3/train.csv','test': None},
    'Dataset4' : {'train': 'Datasets/4/train.csv','test': None},
    'Dataset5' : {'train': 'Datasets/5/train.csv','test': None},
    'Dataset6' : {'train': 'Datasets/6/train.csv','test': None},
    'Dataset7' : {'train': 'Datasets/7/train.csv','test': None},
    'Dataset8' : {'train': 'Datasets/8/train.csv','test': None},
}

LABEL_COL = 'Label'
N_FOLDS = 10
INNER_FOLDS = 3
RANDOM_STATE = 42

# ReliefF Settings
# k = number of top features to keep after ranking
# Try a few values; the best k is selected by inner CV
K_CANDIDATES = [5, 10, 20]  # adjust based on total feature count
RELIEFF_N_NEIGHBORS = 10          # ReliefF neighbourhood size

$\textbf{Step 2: Classifier Definition with Hyperparameter Grids}$

In [28]:
CLASSIFIERS = {
    'SVM': (
            CalibratedClassifierCV(LinearSVC(random_state=RANDOM_STATE, max_iter=2000)),
            {'classifier__estimator__C': [1, 10]}
            ),
    'kNN': (
        KNeighborsClassifier(),
        {
            'classifier__n_neighbors': [3, 5, 11, 21],
            'classifier__weights':     ['uniform', 'distance'],
        }
    ),
    'Decision Tree': (
        DecisionTreeClassifier(random_state=RANDOM_STATE),
        {
            'classifier__max_depth':        [5, 10, 20, None],
            'classifier__min_samples_split': [2, 5, 10],
        }
    ),
    'Random Forest': (
        RandomForestClassifier(random_state=RANDOM_STATE, n_jobs=-1),
        {
            'classifier__n_estimators': [50, 100, 200],
            'classifier__max_depth':    [5, 10, None],
        }
    ),
    'MLP': (
        MLPClassifier(max_iter=500, random_state=RANDOM_STATE, early_stopping=True),
        {
            'classifier__hidden_layer_sizes': [(64,), (128,)],
            'classifier__alpha':              [1e-4, 1e-3],
        }
    ),
}

$\textbf{Step 4: Helper Functions}$

In [29]:
def load_dataset(path, label_col=LABEL_COL):
    df = pd.read_csv(path)
    X = df.drop(columns=[label_col]).values.astype(np.float64) #Dropping the Label Column and converts to float64 Numpy array
    y_raw = df[label_col].values
    le = LabelEncoder()
    y = le.fit_transform(y_raw)
    print(f'  Loaded: {X.shape[0]} samples, {X.shape[1]} features, '
          f'{len(np.unique(y))} classes')
    return X, y, le

def apply_relieff(X_train, y_train, X_test, k, n_neighbors=RELIEFF_N_NEIGHBORS, max_samples=500):
    # Subsample for ReliefF only — avoids distance matrix memory error
    if X_train.shape[0] > max_samples:
        idx = np.random.RandomState(RANDOM_STATE).choice(
            X_train.shape[0], max_samples, replace=False)
        X_relief = X_train[idx]
        y_relief = y_train[idx]
    else:
        X_relief = X_train
        y_relief = y_train

    imputer = SimpleImputer(strategy='mean')
    X_relief_imp = imputer.fit_transform(X_relief)

    selector = ReliefF(n_features_to_select=k, n_neighbors=n_neighbors)
    selector.fit(X_relief_imp, y_relief)
    top_idx = np.argsort(selector.feature_importances_)[::-1][:k]
    return X_train[:, top_idx], X_test[:, top_idx], selector.feature_importances_, top_idx

def build_pipeline(clf):
    return Pipeline([
        ('imputer', SimpleImputer(strategy='mean')),
        ('scaler', StandardScaler()),
        ('classifier', clf),
    ])

def evaluate_classifier(clf, param_grid, X_train, y_train, X_test, y_test):
    pipe = build_pipeline(clf)
    inner_cv = StratifiedKFold(n_splits=INNER_FOLDS, shuffle=True,
                                random_state = RANDOM_STATE)
    gs = GridSearchCV(pipe, param_grid, cv=inner_cv,
                      scoring='f1_macro', n_jobs=-1, refit=True)
    gs.fit(X_train, y_train)
    y_pred = gs.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred, average='macro', zero_division = 0)
    best_params = gs.best_params_
    return acc, f1, best_params

def print_fold_results(fold_idx, n_folds, ds_name, all_results, clf_names, best_k):
    print(f"\n  ── Fold {fold_idx + 1}/{n_folds} Results ({ds_name}) | best_k={best_k} ──")
    
    rows = []
    for phase_name, classifiers in all_results[ds_name].items():
        for clf_name, metrics in classifiers.items():
            if len(metrics['acc']) == 0:
                continue
            rows.append({
                'Phase':      'Baseline' if phase_name == 'baseline' else 'ReliefF',
                'Classifier': clf_name,
                'Accuracy':   f"{np.mean(metrics['acc']):.4f} ± {np.std(metrics['acc']):.4f}",
                'Macro-F1':   f"{np.mean(metrics['f1']):.4f} ± {np.std(metrics['f1']):.4f}",
                'Best Params': metrics['params'][-1],
            })
    
    df = pd.DataFrame(rows)
    pd.set_option('display.max_colwidth', 60)
    display(df)
    print()

$\textbf{Step 5: Main Experiment Loop}$

In [30]:
all_results = {}
relieff_scores = {}

outer_cv = StratifiedKFold(n_splits= N_FOLDS, shuffle=True, random_state=RANDOM_STATE)

for ds_name, paths in DATASETS.items():
    print(f'\n=== Dataset: {ds_name} ===')
    X, y, le = load_dataset(paths['train'])

    all_results[ds_name] = {
        'baseline': {clf: {'acc': [], 'f1': [], 'params': []} for clf in CLASSIFIERS},
        'relieff':  {clf: {'acc': [], 'f1': [], 'params': []} for clf in CLASSIFIERS},
    }
    fold_feature_scores = []

    for fold_idx, (train_idx, test_idx) in enumerate(outer_cv.split(X,y)):
        print(f'  Fold {fold_idx + 1}/{N_FOLDS}', end=' ... ')
        X_train, X_test = X[train_idx], X[test_idx]
        y_train, y_test = y[train_idx], y[test_idx]

         # ── Phase 1: baseline (full features) ────────────────────────────────
        for clf_name, (clf, grid) in CLASSIFIERS.items():
            t0 = time.time()
            acc, f1, params = evaluate_classifier(
                clf, grid, X_train, y_train, X_test, y_test)
            all_results[ds_name]['baseline'][clf_name]['acc'].append(acc)
            all_results[ds_name]['baseline'][clf_name]['f1'].append(f1)
            all_results[ds_name]['baseline'][clf_name]['params'].append(params)
            print(f"    {clf_name}: {time.time()-t0:.1f}s")

        # ── Phase 2: ReliefF — fit on training fold ONLY ─────────────────────      
        print("    Starting ReliefF...", end=" ", flush=True)
        t0 = time.time()
        _, _, importances, sorted_idx = apply_relieff(
            X_train, y_train, X_test, k=1)
        print(f"done ({time.time()-t0:.1f}s)", flush=True)
        # Choose best k by slicing only — no extra ReliefF calls
        best_k, best_k_score = K_CANDIDATES[0], -np.inf
        for k_candidate in K_CANDIDATES:
            if k_candidate > X_train.shape[1]:
                continue
            top_idx = np.argsort(importances)[::-1][:k_candidate]
            Xtr_k, Xte_k = X_train[:, top_idx], X_test[:, top_idx]
            inner = StratifiedKFold(n_splits=3, shuffle=True, random_state=0)
            scores = []
            for itr, ite in inner.split(Xtr_k, y_train):
                rf = RandomForestClassifier(n_estimators=50,
                                            random_state=RANDOM_STATE, n_jobs=-1)
                rf.fit(Xtr_k[itr], y_train[itr])
                scores.append(f1_score(y_train[ite],
                                       rf.predict(Xtr_k[ite]),
                                       average='macro', zero_division=0))
            if np.mean(scores) > best_k_score:
                best_k_score = np.mean(scores)
                best_k = k_candidate

        print(f"    best_k selected: {best_k}", flush=True)
            
        # Slice final features using best_k
        top_idx_final = np.argsort(importances)[::-1][:best_k]
        X_train_r = X_train[:, top_idx_final]
        X_test_r  = X_test[:, top_idx_final]
        fold_feature_scores.append(importances)

        for clf_name, (clf, grid) in CLASSIFIERS.items():
            t0 = time.time()
            acc, f1, params = evaluate_classifier(
                clf, grid, X_train_r, y_train, X_test_r, y_test)
            all_results[ds_name]['relieff'][clf_name]['acc'].append(acc)
            all_results[ds_name]['relieff'][clf_name]['f1'].append(f1)
            all_results[ds_name]['relieff'][clf_name]['params'].append(params)
            print(f"    {clf_name}: {time.time()-t0:.1f}s")

        print('done')
        print_fold_results(fold_idx, N_FOLDS, ds_name, all_results, clf_name, best_k)


    relieff_scores[ds_name] = np.mean(fold_feature_scores, axis=0)
        
# # Average ReliefF scores across folds for plotting
with open('results_checkpoint.pkl', 'wb') as f:
    pickle.dump({'all_results': all_results, 'relieff_scores': relieff_scores}, f)
print(f'  Checkpoint saved for {ds_name}.')

=== Dataset: Dataset1 ===
  Loaded: 9583 samples, 19 features, 4 classes
  Fold 1/10 ...     SVM: 4.5s
    kNN: 1.2s
    Decision Tree: 0.5s
    Random Forest: 6.0s
    MLP: 9.4s
    Starting ReliefF... done (0.8s)
    best_k selected: 5
    SVM: 0.6s
    kNN: 0.4s
    Decision Tree: 0.2s
    Random Forest: 4.6s
    MLP: 2.0s
done

  ── Fold 1/10 Results (Dataset1) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9864 ± 0.0000,0.7372 ± 0.0000,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9906 ± 0.0000,0.7368 ± 0.0000,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9823 ± 0.0000,0.7329 ± 0.0000,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8467 ± 0.0000,0.4786 ± 0.0000,{'classifier__estimator__C': 10}
6,ReliefF,kNN,0.9990 ± 0.0000,0.9990 ± 0.0000,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.8394 ± 0.0000,0.4419 ± 0.0000,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 2/10 ...     SVM: 1.6s
    kNN: 1.2s
    Decision Tree: 0.6s
    Random Forest: 6.1s
    MLP: 8.8s
    Starting ReliefF... done (0.8s)
    best_k selected: 5
    SVM: 0.5s
    kNN: 0.4s
    Decision Tree: 0.2s
    Random Forest: 4.5s
    MLP: 2.1s
done

  ── Fold 2/10 Results (Dataset1) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9870 ± 0.0005,0.7357 ± 0.0015,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9911 ± 0.0005,0.7356 ± 0.0012,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9838 ± 0.0016,0.7326 ± 0.0004,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."
5,ReliefF,SVM,0.8337 ± 0.0130,0.3521 ± 0.1266,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9984 ± 0.0005,0.9941 ± 0.0049,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.8796 ± 0.0401,0.5405 ± 0.0986,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 3/10 ...     SVM: 1.5s
    kNN: 1.2s
    Decision Tree: 0.6s
    Random Forest: 6.4s
    MLP: 7.7s
    Starting ReliefF... done (0.7s)
    best_k selected: 5
    SVM: 0.8s
    kNN: 0.6s
    Decision Tree: 0.2s
    Random Forest: 5.2s
    MLP: 2.3s
done

  ── Fold 3/10 Results (Dataset1) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9847 ± 0.0032,0.7326 ± 0.0045,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9885 ± 0.0037,0.7324 ± 0.0046,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9809 ± 0.0044,0.7252 ± 0.0104,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8359 ± 0.0111,0.3847 ± 0.1132,{'classifier__estimator__C': 10}
6,ReliefF,kNN,0.9979 ± 0.0009,0.9107 ± 0.1181,"{'classifier__n_neighbors': 21, 'classifier__weights': '..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.8648 ± 0.0389,0.4967 ± 0.1016,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 4/10 ...     SVM: 1.1s
    kNN: 0.9s
    Decision Tree: 0.6s
    Random Forest: 8.0s
    MLP: 10.4s
    Starting ReliefF... done (0.9s)
    best_k selected: 5
    SVM: 0.6s
    kNN: 0.4s
    Decision Tree: 0.2s
    Random Forest: 5.9s
    MLP: 3.3s
done

  ── Fold 4/10 Results (Dataset1) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9844 ± 0.0029,0.7938 ± 0.1060,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9870 ± 0.0042,0.7908 ± 0.1012,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9794 ± 0.0046,0.7838 ± 0.1019,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8323 ± 0.0115,0.3637 ± 0.1046,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9977 ± 0.0009,0.9320 ± 0.1087,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.8751 ± 0.0381,0.5786 ± 0.1669,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 5/10 ...     SVM: 1.8s
    kNN: 1.2s
    Decision Tree: 0.7s
    Random Forest: 7.2s
    MLP: 12.4s
    Starting ReliefF... done (0.8s)
    best_k selected: 5
    SVM: 0.8s
    kNN: 0.5s
    Decision Tree: 0.3s
    Random Forest: 5.9s
    MLP: 2.2s
done

  ── Fold 5/10 Results (Dataset1) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9846 ± 0.0026,0.8311 ± 0.1207,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9864 ± 0.0039,0.8261 ± 0.1148,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9804 ± 0.0045,0.8228 ± 0.1200,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8304 ± 0.0110,0.3511 ± 0.0968,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9977 ± 0.0008,0.9450 ± 0.1007,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.8823 ± 0.0370,0.6311 ± 0.1825,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 6/10 ...     SVM: 2.0s
    kNN: 1.7s
    Decision Tree: 0.6s
    Random Forest: 8.4s
    MLP: 11.2s
    Starting ReliefF... done (0.9s)
    best_k selected: 5
    SVM: 0.5s
    kNN: 0.4s
    Decision Tree: 0.2s
    Random Forest: 6.5s
    MLP: 3.1s
done

  ── Fold 6/10 Results (Dataset1) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9842 ± 0.0025,0.8552 ± 0.1226,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9863 ± 0.0036,0.8519 ± 0.1196,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9797 ± 0.0045,0.8459 ± 0.1211,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8291 ± 0.0104,0.3428 ± 0.0904,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9981 ± 0.0011,0.9542 ± 0.0942,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.8879 ± 0.0360,0.6686 ± 0.1865,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 7/10 ...     SVM: 2.3s
    kNN: 1.9s
    Decision Tree: 0.8s
    Random Forest: 6.9s
    MLP: 10.3s
    Starting ReliefF... done (0.9s)
    best_k selected: 5
    SVM: 0.6s
    kNN: 0.5s
    Decision Tree: 0.2s
    Random Forest: 5.1s
    MLP: 2.8s
done

  ── Fold 7/10 Results (Dataset1) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9830 ± 0.0037,0.8695 ± 0.1188,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9860 ± 0.0034,0.8692 ± 0.1186,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9790 ± 0.0044,0.8621 ± 0.1189,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8316 ± 0.0114,0.3840 ± 0.1311,{'classifier__estimator__C': 10}
6,ReliefF,kNN,0.9984 ± 0.0012,0.9607 ± 0.0886,"{'classifier__n_neighbors': 11, 'classifier__weights': '..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.8806 ± 0.0377,0.6521 ± 0.1773,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 8/10 ...     SVM: 1.8s
    kNN: 1.5s
    Decision Tree: 0.6s
    Random Forest: 6.5s
    MLP: 9.3s
    Starting ReliefF... done (0.9s)
    best_k selected: 5
    SVM: 0.5s
    kNN: 0.4s
    Decision Tree: 0.2s
    Random Forest: 5.3s
    MLP: 2.8s
done

  ── Fold 8/10 Results (Dataset1) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9819 ± 0.0046,0.8507 ± 0.1217,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9857 ± 0.0033,0.8519 ± 0.1201,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9999 ± 0.0003,0.9999 ± 0.0003,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9782 ± 0.0046,0.8747 ± 0.1162,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8304 ± 0.0111,0.3642 ± 0.1333,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9986 ± 0.0013,0.9657 ± 0.0839,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.8847 ± 0.0369,0.6495 ± 0.1660,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 9/10 ...     SVM: 1.9s
    kNN: 1.3s
    Decision Tree: 0.7s
    Random Forest: 6.4s
    MLP: 9.5s
    Starting ReliefF... done (0.9s)
    best_k selected: 5
    SVM: 0.5s
    kNN: 0.6s
    Decision Tree: 0.2s
    Random Forest: 5.8s
    MLP: 2.9s
done

  ── Fold 9/10 Results (Dataset1) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9808 ± 0.0054,0.8348 ± 0.1232,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9854 ± 0.0032,0.8368 ± 0.1210,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9999 ± 0.0003,0.9999 ± 0.0003,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9769 ± 0.0057,0.8546 ± 0.1234,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8296 ± 0.0108,0.3488 ± 0.1330,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9985 ± 0.0012,0.9692 ± 0.0798,"{'classifier__n_neighbors': 21, 'classifier__weights': '..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.8879 ± 0.0360,0.6475 ± 0.1566,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 10/10 ...     SVM: 2.1s
    kNN: 1.5s
    Decision Tree: 0.7s
    Random Forest: 7.3s
    MLP: 8.4s
    Starting ReliefF... done (0.9s)
    best_k selected: 5
    SVM: 1.1s
    kNN: 0.7s
    Decision Tree: 0.3s
    Random Forest: 6.5s
    MLP: 2.8s
done

  ── Fold 10/10 Results (Dataset1) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9805 ± 0.0051,0.8237 ± 0.1216,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9856 ± 0.0031,0.8261 ± 0.1192,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9996 ± 0.0010,0.9996 ± 0.0009,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9766 ± 0.0055,0.8402 ± 0.1248,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."
5,ReliefF,SVM,0.8289 ± 0.0104,0.3365 ± 0.1315,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9985 ± 0.0012,0.9722 ± 0.0762,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.8905 ± 0.0350,0.6461 ± 0.1486,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

=== Dataset: Dataset2 ===
  Loaded: 9583 samples, 19 features, 4 classes
  Fold 1/10 ...     SVM: 1.9s
    kNN: 1.4s
    Decision Tree: 0.7s
    Random Forest: 7.3s
    MLP: 7.9s
    Starting ReliefF... done (1.2s)
    best_k selected: 10
    SVM: 0.7s
    kNN: 0.9s
    Decision Tree: 0.3s
    Random Forest: 7.3s
    MLP: 7.0s
done

  ── Fold 1/10 Results (Dataset2) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9270 ± 0.0000,0.4342 ± 0.0000,{'classifier__estimator__C': 1}
1,Baseline,kNN,0.9635 ± 0.0000,0.6113 ± 0.0000,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.9677 ± 0.0000,0.6928 ± 0.0000,"{'classifier__max_depth': None, 'classifier__min_samples..."
3,Baseline,Random Forest,0.9708 ± 0.0000,0.6532 ± 0.0000,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9531 ± 0.0000,0.5230 ± 0.0000,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."
5,ReliefF,SVM,0.8676 ± 0.0000,0.3269 ± 0.0000,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9625 ± 0.0000,0.6720 ± 0.0000,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,0.9677 ± 0.0000,0.6503 ± 0.0000,"{'classifier__max_depth': 20, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,0.9687 ± 0.0000,0.6740 ± 0.0000,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.9395 ± 0.0000,0.4527 ± 0.0000,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 2/10 ...     SVM: 1.6s
    kNN: 1.0s
    Decision Tree: 0.6s
    Random Forest: 6.8s
    MLP: 8.2s
    Starting ReliefF... done (0.9s)
    best_k selected: 10
    SVM: 0.8s
    kNN: 0.7s
    Decision Tree: 0.4s
    Random Forest: 6.1s
    MLP: 6.4s
done

  ── Fold 2/10 Results (Dataset2) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9213 ± 0.0057,0.4261 ± 0.0081,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9526 ± 0.0109,0.5877 ± 0.0235,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.9593 ± 0.0083,0.6201 ± 0.0727,"{'classifier__max_depth': None, 'classifier__min_samples..."
3,Baseline,Random Forest,0.9625 ± 0.0083,0.6205 ± 0.0327,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9447 ± 0.0083,0.4860 ± 0.0369,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8697 ± 0.0021,0.3330 ± 0.0061,{'classifier__estimator__C': 10}
6,ReliefF,kNN,0.9515 ± 0.0109,0.6366 ± 0.0354,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,0.9567 ± 0.0109,0.6188 ± 0.0314,"{'classifier__max_depth': 20, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,0.9604 ± 0.0083,0.6419 ± 0.0321,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.9312 ± 0.0083,0.4422 ± 0.0105,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."

  Fold 3/10 ...     SVM: 1.5s
    kNN: 1.3s
    Decision Tree: 0.7s
    Random Forest: 6.3s
    MLP: 9.6s
    Starting ReliefF... done (1.0s)
    best_k selected: 10
    SVM: 1.1s
    kNN: 0.8s
    Decision Tree: 0.4s
    Random Forest: 6.7s
    MLP: 4.0s
done

  ── Fold 3/10 Results (Dataset2) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9221 ± 0.0048,0.4271 ± 0.0067,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9552 ± 0.0097,0.5812 ± 0.0213,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.9590 ± 0.0068,0.5988 ± 0.0666,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9618 ± 0.0069,0.5861 ± 0.0554,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9447 ± 0.0068,0.4758 ± 0.0334,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8683 ± 0.0026,0.3293 ± 0.0073,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9527 ± 0.0091,0.6126 ± 0.0446,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,0.9586 ± 0.0093,0.6139 ± 0.0266,"{'classifier__max_depth': None, 'classifier__min_samples..."
8,ReliefF,Random Forest,0.9607 ± 0.0068,0.6232 ± 0.0372,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.9183 ± 0.0194,0.4206 ± 0.0318,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 4/10 ...     SVM: 2.0s
    kNN: 1.2s
    Decision Tree: 0.8s
    Random Forest: 8.3s
    MLP: 9.6s
    Starting ReliefF... done (1.1s)
    best_k selected: 10
    SVM: 0.7s
    kNN: 0.8s
    Decision Tree: 0.4s
    Random Forest: 8.0s
    MLP: 6.4s
done

  ── Fold 4/10 Results (Dataset2) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9223 ± 0.0042,0.4271 ± 0.0058,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9536 ± 0.0088,0.5947 ± 0.0298,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.9585 ± 0.0060,0.6054 ± 0.0588,"{'classifier__max_depth': 20, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9614 ± 0.0060,0.5922 ± 0.0491,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9447 ± 0.0059,0.4841 ± 0.0323,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8621 ± 0.0110,0.3211 ± 0.0155,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9507 ± 0.0086,0.6059 ± 0.0403,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,0.9567 ± 0.0087,0.6126 ± 0.0232,"{'classifier__max_depth': 20, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,0.9575 ± 0.0081,0.6168 ± 0.0341,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.9199 ± 0.0171,0.4237 ± 0.0280,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 5/10 ...     SVM: 1.6s
    kNN: 1.0s
    Decision Tree: 0.6s
    Random Forest: 6.5s
    MLP: 6.7s
    Starting ReliefF... done (1.1s)
    best_k selected: 10
    SVM: 1.1s
    kNN: 0.8s
    Decision Tree: 0.4s
    Random Forest: 5.5s
    MLP: 6.1s
done

  ── Fold 5/10 Results (Dataset2) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9218 ± 0.0039,0.4257 ± 0.0060,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9531 ± 0.0079,0.5891 ± 0.0289,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.9560 ± 0.0074,0.5845 ± 0.0672,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9591 ± 0.0071,0.5901 ± 0.0441,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9443 ± 0.0053,0.4835 ± 0.0289,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8610 ± 0.0100,0.3172 ± 0.0159,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9476 ± 0.0099,0.5891 ± 0.0493,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,0.9547 ± 0.0088,0.6036 ± 0.0274,"{'classifier__max_depth': None, 'classifier__min_samples..."
8,ReliefF,Random Forest,0.9553 ± 0.0085,0.6074 ± 0.0358,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.9218 ± 0.0157,0.4259 ± 0.0255,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 6/10 ...     SVM: 1.0s
    kNN: 1.0s
    Decision Tree: 0.6s
    Random Forest: 6.2s
    MLP: 8.1s
    Starting ReliefF... done (1.0s)
    best_k selected: 10
    SVM: 0.9s
    kNN: 1.1s
    Decision Tree: 0.5s
    Random Forest: 7.8s
    MLP: 7.7s
done

  ── Fold 6/10 Results (Dataset2) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9237 ± 0.0056,0.4280 ± 0.0076,{'classifier__estimator__C': 1}
1,Baseline,kNN,0.9543 ± 0.0077,0.5936 ± 0.0282,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.9583 ± 0.0085,0.5984 ± 0.0688,"{'classifier__max_depth': None, 'classifier__min_samples..."
3,Baseline,Random Forest,0.9610 ± 0.0078,0.5893 ± 0.0403,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9452 ± 0.0053,0.4880 ± 0.0282,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8619 ± 0.0094,0.3171 ± 0.0145,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9478 ± 0.0090,0.5796 ± 0.0498,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,0.9558 ± 0.0084,0.6038 ± 0.0250,"{'classifier__max_depth': None, 'classifier__min_samples..."
8,ReliefF,Random Forest,0.9570 ± 0.0086,0.6058 ± 0.0329,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.9230 ± 0.0146,0.4276 ± 0.0235,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 7/10 ...     SVM: 1.2s
    kNN: 0.9s
    Decision Tree: 0.6s
    Random Forest: 5.3s
    MLP: 6.2s
    Starting ReliefF... done (0.8s)
    best_k selected: 10
    SVM: 1.2s
    kNN: 1.1s
    Decision Tree: 0.5s
    Random Forest: 6.6s
    MLP: 5.0s
done

  ── Fold 7/10 Results (Dataset2) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9225 ± 0.0059,0.4259 ± 0.0087,{'classifier__estimator__C': 1}
1,Baseline,kNN,0.9539 ± 0.0072,0.5932 ± 0.0261,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.9586 ± 0.0079,0.5848 ± 0.0718,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9614 ± 0.0073,0.5923 ± 0.0381,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9446 ± 0.0052,0.4826 ± 0.0293,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."
5,ReliefF,SVM,0.8615 ± 0.0087,0.3166 ± 0.0135,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9487 ± 0.0086,0.5834 ± 0.0470,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,0.9557 ± 0.0078,0.6034 ± 0.0232,"{'classifier__max_depth': 20, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,0.9565 ± 0.0081,0.6012 ± 0.0325,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.9209 ± 0.0145,0.4240 ± 0.0235,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 8/10 ...     SVM: 1.5s
    kNN: 1.1s
    Decision Tree: 0.7s
    Random Forest: 6.1s
    MLP: 6.6s
    Starting ReliefF... done (1.0s)
    best_k selected: 10
    SVM: 0.7s
    kNN: 0.8s
    Decision Tree: 0.4s
    Random Forest: 5.6s
    MLP: 7.9s
done

  ── Fold 8/10 Results (Dataset2) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9234 ± 0.0061,0.4270 ± 0.0086,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9547 ± 0.0071,0.5930 ± 0.0244,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.9588 ± 0.0074,0.5796 ± 0.0686,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9617 ± 0.0068,0.5903 ± 0.0360,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9450 ± 0.0050,0.4850 ± 0.0282,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8608 ± 0.0084,0.3135 ± 0.0150,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9491 ± 0.0082,0.5835 ± 0.0440,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,0.9564 ± 0.0075,0.6011 ± 0.0226,"{'classifier__max_depth': 20, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,0.9573 ± 0.0079,0.6024 ± 0.0306,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.9238 ± 0.0156,0.4283 ± 0.0248,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 9/10 ...     SVM: 1.7s
    kNN: 1.1s
    Decision Tree: 0.7s
    Random Forest: 6.5s
    MLP: 6.5s
    Starting ReliefF... done (0.9s)
    best_k selected: 10
    SVM: 0.7s
    kNN: 0.7s
    Decision Tree: 0.3s
    Random Forest: 5.5s
    MLP: 5.7s
done

  ── Fold 9/10 Results (Dataset2) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9242 ± 0.0061,0.4279 ± 0.0085,{'classifier__estimator__C': 1}
1,Baseline,kNN,0.9551 ± 0.0068,0.6021 ± 0.0345,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.9591 ± 0.0070,0.5811 ± 0.0648,"{'classifier__max_depth': 20, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9626 ± 0.0069,0.6016 ± 0.0466,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9457 ± 0.0052,0.4880 ± 0.0279,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."
5,ReliefF,SVM,0.8614 ± 0.0081,0.3147 ± 0.0145,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9489 ± 0.0077,0.5836 ± 0.0415,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,0.9564 ± 0.0071,0.5987 ± 0.0223,"{'classifier__max_depth': None, 'classifier__min_samples..."
8,ReliefF,Random Forest,0.9576 ± 0.0075,0.6027 ± 0.0289,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.9228 ± 0.0150,0.4263 ± 0.0240,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 10/10 ...     SVM: 1.4s
    kNN: 1.0s
    Decision Tree: 0.7s
    Random Forest: 6.4s
    MLP: 6.8s
    Starting ReliefF... done (0.8s)
    best_k selected: 10
    SVM: 0.8s
    kNN: 0.7s
    Decision Tree: 0.4s
    Random Forest: 5.2s
    MLP: 2.7s
done

  ── Fold 10/10 Results (Dataset2) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9247 ± 0.0059,0.4286 ± 0.0084,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9552 ± 0.0064,0.5967 ± 0.0365,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.9595 ± 0.0068,0.5878 ± 0.0647,"{'classifier__max_depth': 20, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9625 ± 0.0066,0.6011 ± 0.0443,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9449 ± 0.0055,0.4864 ± 0.0269,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."
5,ReliefF,SVM,0.8617 ± 0.0077,0.3151 ± 0.0138,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9492 ± 0.0074,0.5760 ± 0.0455,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,0.9569 ± 0.0069,0.5947 ± 0.0243,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,0.9579 ± 0.0072,0.5991 ± 0.0294,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.9201 ± 0.0164,0.4222 ± 0.0259,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

=== Dataset: Dataset3 ===
  Loaded: 9583 samples, 19 features, 4 classes
  Fold 1/10 ...     SVM: 1.2s
    kNN: 1.0s
    Decision Tree: 0.7s
    Random Forest: 6.5s
    MLP: 5.1s
    Starting ReliefF... done (1.0s)
    best_k selected: 10
    SVM: 0.6s
    kNN: 0.6s
    Decision Tree: 0.3s
    Random Forest: 5.2s
    MLP: 3.9s
done

  ── Fold 1/10 Results (Dataset3) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.8509 ± 0.0000,0.3169 ± 0.0000,{'classifier__estimator__C': 1}
1,Baseline,kNN,0.8853 ± 0.0000,0.5925 ± 0.0000,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.8770 ± 0.0000,0.5504 ± 0.0000,"{'classifier__max_depth': 20, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.8811 ± 0.0000,0.5495 ± 0.0000,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.8613 ± 0.0000,0.4472 ± 0.0000,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8446 ± 0.0000,0.2385 ± 0.0000,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.8686 ± 0.0000,0.5151 ± 0.0000,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,0.8644 ± 0.0000,0.4996 ± 0.0000,"{'classifier__max_depth': 20, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,0.8728 ± 0.0000,0.5357 ± 0.0000,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.8498 ± 0.0000,0.2816 ± 0.0000,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 2/10 ...     SVM: 1.3s
    kNN: 0.9s
    Decision Tree: 0.6s
    Random Forest: 4.8s
    MLP: 2.7s
    Starting ReliefF... done (0.9s)
    best_k selected: 5
    SVM: 0.3s
    kNN: 0.3s
    Decision Tree: 0.2s
    Random Forest: 3.7s
    MLP: 1.0s
done

  ── Fold 2/10 Results (Dataset3) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.8498 ± 0.0010,0.3080 ± 0.0089,{'classifier__estimator__C': 1}
1,Baseline,kNN,0.8895 ± 0.0042,0.5814 ± 0.0111,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.8796 ± 0.0026,0.5409 ± 0.0095,"{'classifier__max_depth': 20, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.8858 ± 0.0047,0.5478 ± 0.0017,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.8571 ± 0.0042,0.3886 ± 0.0586,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8441 ± 0.0005,0.2336 ± 0.0048,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.8790 ± 0.0104,0.5410 ± 0.0259,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,0.8728 ± 0.0083,0.5149 ± 0.0154,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,0.8796 ± 0.0068,0.5398 ± 0.0041,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.8467 ± 0.0031,0.2552 ± 0.0264,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 3/10 ...     SVM: 1.0s
    kNN: 0.8s
    Decision Tree: 0.6s
    Random Forest: 4.8s
    MLP: 4.5s
    Starting ReliefF... done (0.8s)
    best_k selected: 10
    SVM: 0.5s
    kNN: 0.5s
    Decision Tree: 0.3s
    Random Forest: 4.3s
    MLP: 3.8s
done

  ── Fold 3/10 Results (Dataset3) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.8523 ± 0.0035,0.3127 ± 0.0099,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.8888 ± 0.0035,0.5875 ± 0.0125,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.8849 ± 0.0079,0.5679 ± 0.0389,"{'classifier__max_depth': 20, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.8877 ± 0.0047,0.5629 ± 0.0213,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.8648 ± 0.0113,0.4310 ± 0.0768,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."
5,ReliefF,SVM,0.8439 ± 0.0005,0.2321 ± 0.0045,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.8790 ± 0.0085,0.5451 ± 0.0219,"{'classifier__n_neighbors': 11, 'classifier__weights': '..."
7,ReliefF,Decision Tree,0.8759 ± 0.0081,0.5340 ± 0.0297,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,0.8815 ± 0.0062,0.5534 ± 0.0195,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.8491 ± 0.0043,0.2806 ± 0.0419,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."

  Fold 4/10 ...     SVM: 1.0s
    kNN: 0.8s
    Decision Tree: 0.6s
    Random Forest: 4.7s
    MLP: 3.2s
    Starting ReliefF... done (0.8s)
    best_k selected: 10
    SVM: 0.5s
    kNN: 0.6s
    Decision Tree: 0.3s

/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(

    Random Forest: 4.1s
    MLP: 2.0s
done

  ── Fold 4/10 Results (Dataset3) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.8519 ± 0.0031,0.3143 ± 0.0090,{'classifier__estimator__C': 1}
1,Baseline,kNN,0.8884 ± 0.0031,0.5881 ± 0.0109,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.8840 ± 0.0071,0.5632 ± 0.0347,"{'classifier__max_depth': 20, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.8902 ± 0.0059,0.5685 ± 0.0209,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
4,Baseline,MLP,0.8681 ± 0.0113,0.4455 ± 0.0711,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."
5,ReliefF,SVM,0.8446 ± 0.0012,0.2383 ± 0.0114,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.8801 ± 0.0076,0.5472 ± 0.0194,"{'classifier__n_neighbors': 21, 'classifier__weights': '..."
7,ReliefF,Decision Tree,0.8777 ± 0.0077,0.5403 ± 0.0280,"{'classifier__max_depth': 20, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,0.8814 ± 0.0053,0.5518 ± 0.0171,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.8495 ± 0.0038,0.2885 ± 0.0388,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 5/10 ...     SVM: 1.1s
    kNN: 0.8s
    Decision Tree: 0.6s
    Random Forest: 4.9s
    MLP: 3.1s
    Starting ReliefF... done (0.8s)
    best_k selected: 10
    SVM: 0.5s
    kNN: 0.5s
    Decision Tree: 0.3s
    Random Forest: 4.1s
    MLP: 3.4s
done

  ── Fold 5/10 Results (Dataset3) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.8506 ± 0.0038,0.3120 ± 0.0093,{'classifier__estimator__C': 1}
1,Baseline,kNN,0.8884 ± 0.0028,0.5862 ± 0.0104,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.8838 ± 0.0063,0.5624 ± 0.0311,"{'classifier__max_depth': 20, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.8911 ± 0.0056,0.5732 ± 0.0209,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.8727 ± 0.0138,0.4666 ± 0.0763,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8446 ± 0.0011,0.2364 ± 0.0109,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.8809 ± 0.0070,0.5476 ± 0.0173,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,0.8792 ± 0.0075,0.5453 ± 0.0269,"{'classifier__max_depth': 20, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,0.8821 ± 0.0050,0.5531 ± 0.0155,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.8579 ± 0.0171,0.3327 ± 0.0950,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 6/10 ...     SVM: 1.0s
    kNN: 0.8s
    Decision Tree: 0.6s
    Random Forest: 5.0s
    MLP: 4.3s
    Starting ReliefF... done (0.8s)
    best_k selected: 10
    SVM: 0.5s
    kNN: 0.6s
    Decision Tree: 0.3s
    Random Forest: 4.5s
    MLP: 3.3s
done

  ── Fold 6/10 Results (Dataset3) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.8505 ± 0.0035,0.3090 ± 0.0108,{'classifier__estimator__C': 1}
1,Baseline,kNN,0.8899 ± 0.0043,0.5906 ± 0.0137,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.8868 ± 0.0089,0.5716 ± 0.0350,"{'classifier__max_depth': 20, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.8934 ± 0.0073,0.5821 ± 0.0276,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.8743 ± 0.0131,0.4764 ± 0.0730,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8444 ± 0.0011,0.2352 ± 0.0104,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.8832 ± 0.0082,0.5538 ± 0.0210,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,0.8826 ± 0.0103,0.5575 ± 0.0368,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,0.8830 ± 0.0050,0.5528 ± 0.0142,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.8599 ± 0.0162,0.3481 ± 0.0933,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."

  Fold 7/10 ...     SVM: 1.0s
    kNN: 0.8s
    Decision Tree: 0.6s
    Random Forest: 4.7s
    MLP: 2.9s
    Starting ReliefF... done (0.8s)
    best_k selected: 10
    SVM: 0.5s
    kNN: 0.6s
    Decision Tree: 0.3s
    Random Forest: 4.4s
    MLP: 2.0s
done

  ── Fold 7/10 Results (Dataset3) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.8505 ± 0.0032,0.3074 ± 0.0107,{'classifier__estimator__C': 1}
1,Baseline,kNN,0.8912 ± 0.0050,0.5914 ± 0.0128,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.8887 ± 0.0094,0.5743 ± 0.0331,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.8940 ± 0.0069,0.5845 ± 0.0262,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.8726 ± 0.0128,0.4605 ± 0.0781,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."
5,ReliefF,SVM,0.8445 ± 0.0011,0.2357 ± 0.0097,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.8830 ± 0.0076,0.5512 ± 0.0205,"{'classifier__n_neighbors': 11, 'classifier__weights': '..."
7,ReliefF,Decision Tree,0.8833 ± 0.0097,0.5580 ± 0.0341,"{'classifier__max_depth': 20, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,0.8837 ± 0.0050,0.5484 ± 0.0169,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.8587 ± 0.0153,0.3419 ± 0.0877,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 8/10 ...     SVM: 1.0s
    kNN: 0.8s
    Decision Tree: 0.6s
    Random Forest: 4.7s
    MLP: 3.3s
    Starting ReliefF... done (0.8s)
    best_k selected: 10
    SVM: 0.5s
    kNN: 0.6s
    Decision Tree: 0.3s
    Random Forest: 4.1s
    MLP: 2.6s
done

  ── Fold 8/10 Results (Dataset3) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.8505 ± 0.0030,0.3049 ± 0.0120,{'classifier__estimator__C': 1}
1,Baseline,kNN,0.8915 ± 0.0048,0.5948 ± 0.0149,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.8897 ± 0.0092,0.5757 ± 0.0312,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.8957 ± 0.0078,0.5902 ± 0.0289,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.8702 ± 0.0135,0.4393 ± 0.0920,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."
5,ReliefF,SVM,0.8445 ± 0.0010,0.2348 ± 0.0093,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.8835 ± 0.0072,0.5522 ± 0.0193,"{'classifier__n_neighbors': 21, 'classifier__weights': '..."
7,ReliefF,Decision Tree,0.8838 ± 0.0091,0.5602 ± 0.0324,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,0.8847 ± 0.0053,0.5519 ± 0.0182,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.8573 ± 0.0147,0.3372 ± 0.0829,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."

  Fold 9/10 ...     SVM: 0.9s
    kNN: 0.8s
    Decision Tree: 0.6s
    Random Forest: 4.6s
    MLP: 2.8s
    Starting ReliefF... done (0.9s)
    best_k selected: 10
    SVM: 0.5s
    kNN: 0.5s
    Decision Tree: 0.3s
    Random Forest: 4.1s
    MLP: 4.7s
done

  ── Fold 9/10 Results (Dataset3) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.8508 ± 0.0029,0.3072 ± 0.0130,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.8906 ± 0.0052,0.5949 ± 0.0141,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.8894 ± 0.0087,0.5756 ± 0.0294,"{'classifier__max_depth': None, 'classifier__min_samples..."
3,Baseline,Random Forest,0.8948 ± 0.0077,0.5895 ± 0.0273,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.8684 ± 0.0137,0.4249 ± 0.0958,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."
5,ReliefF,SVM,0.8448 ± 0.0011,0.2362 ± 0.0096,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.8828 ± 0.0071,0.5514 ± 0.0184,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,0.8826 ± 0.0093,0.5567 ± 0.0321,"{'classifier__max_depth': None, 'classifier__min_samples..."
8,ReliefF,Random Forest,0.8842 ± 0.0052,0.5506 ± 0.0176,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.8590 ± 0.0147,0.3479 ± 0.0839,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 10/10 ...     SVM: 1.0s
    kNN: 0.8s
    Decision Tree: 0.6s
    Random Forest: 4.9s
    MLP: 3.9s
    Starting ReliefF... done (0.8s)
    best_k selected: 10
    SVM: 0.6s
    kNN: 0.5s
    Decision Tree: 0.3s
    Random Forest: 4.4s
    MLP: 2.7s
done

  ── Fold 10/10 Results (Dataset3) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.8510 ± 0.0029,0.3069 ± 0.0123,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.8911 ± 0.0052,0.5961 ± 0.0138,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.8901 ± 0.0085,0.5758 ± 0.0279,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.8949 ± 0.0073,0.5892 ± 0.0259,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.8673 ± 0.0135,0.4144 ± 0.0962,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."
5,ReliefF,SVM,0.8447 ± 0.0011,0.2372 ± 0.0095,{'classifier__estimator__C': 10}
6,ReliefF,kNN,0.8833 ± 0.0070,0.5549 ± 0.0204,"{'classifier__n_neighbors': 11, 'classifier__weights': '..."
7,ReliefF,Decision Tree,0.8832 ± 0.0090,0.5605 ± 0.0325,"{'classifier__max_depth': None, 'classifier__min_samples..."
8,ReliefF,Random Forest,0.8852 ± 0.0058,0.5555 ± 0.0222,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.8598 ± 0.0141,0.3567 ± 0.0838,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

=== Dataset: Dataset4 ===
  Loaded: 9583 samples, 19 features, 4 classes
  Fold 1/10 ...     SVM: 0.9s
    kNN: 0.8s
    Decision Tree: 0.6s
    Random Forest: 4.8s
    MLP: 2.4s
    Starting ReliefF... done (0.8s)
    best_k selected: 10
    SVM: 0.5s
    kNN: 0.6s
    Decision Tree: 0.4s
    Random Forest: 4.3s
    MLP: 2.1s
done

  ── Fold 1/10 Results (Dataset4) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.8603 ± 0.0000,0.2891 ± 0.0000,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.8707 ± 0.0000,0.5146 ± 0.0000,"{'classifier__n_neighbors': 3, 'classifier__weights': 'u..."
2,Baseline,Decision Tree,0.8634 ± 0.0000,0.4645 ± 0.0000,"{'classifier__max_depth': None, 'classifier__min_samples..."
3,Baseline,Random Forest,0.8665 ± 0.0000,0.5116 ± 0.0000,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.8665 ± 0.0000,0.4067 ± 0.0000,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8540 ± 0.0000,0.2377 ± 0.0000,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.8728 ± 0.0000,0.5166 ± 0.0000,"{'classifier__n_neighbors': 3, 'classifier__weights': 'u..."
7,ReliefF,Decision Tree,0.8717 ± 0.0000,0.5217 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,0.8749 ± 0.0000,0.5531 ± 0.0000,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.8519 ± 0.0000,0.2899 ± 0.0000,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 2/10 ...     SVM: 1.1s
    kNN: 0.8s
    Decision Tree: 0.6s
    Random Forest: 4.8s
    MLP: 2.3s
    Starting ReliefF... done (0.9s)
    best_k selected: 10
    SVM: 0.7s
    kNN: 0.5s
    Decision Tree: 0.3s
    Random Forest: 4.0s
    MLP: 1.8s
done

  ── Fold 2/10 Results (Dataset4) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.8551 ± 0.0052,0.2797 ± 0.0094,{'classifier__estimator__C': 1}
1,Baseline,kNN,0.8686 ± 0.0021,0.5080 ± 0.0066,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.8681 ± 0.0047,0.4965 ± 0.0320,"{'classifier__max_depth': 20, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.8686 ± 0.0021,0.5155 ± 0.0038,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
4,Baseline,MLP,0.8603 ± 0.0063,0.3256 ± 0.0811,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."
5,ReliefF,SVM,0.8566 ± 0.0026,0.2619 ± 0.0242,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.8670 ± 0.0057,0.5170 ± 0.0005,"{'classifier__n_neighbors': 3, 'classifier__weights': 'u..."
7,ReliefF,Decision Tree,0.8665 ± 0.0052,0.5278 ± 0.0062,"{'classifier__max_depth': 20, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,0.8629 ± 0.0120,0.5058 ± 0.0473,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.8535 ± 0.0016,0.3046 ± 0.0147,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 3/10 ...     SVM: 1.0s
    kNN: 0.8s
    Decision Tree: 0.6s
    Random Forest: 5.0s
    MLP: 2.2s
    Starting ReliefF... done (0.8s)
    best_k selected: 10
    SVM: 0.5s
    kNN: 0.5s
    Decision Tree: 0.3s
    Random Forest: 4.1s
    MLP: 2.0s
done

  ── Fold 3/10 Results (Dataset4) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.8551 ± 0.0043,0.2849 ± 0.0107,{'classifier__estimator__C': 1}
1,Baseline,kNN,0.8672 ± 0.0026,0.4991 ± 0.0138,"{'classifier__n_neighbors': 3, 'classifier__weights': 'u..."
2,Baseline,Decision Tree,0.8676 ± 0.0039,0.5066 ± 0.0298,"{'classifier__max_depth': None, 'classifier__min_samples..."
3,Baseline,Random Forest,0.8686 ± 0.0017,0.5159 ± 0.0032,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.8624 ± 0.0059,0.3552 ± 0.0783,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8551 ± 0.0031,0.2513 ± 0.0249,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.8693 ± 0.0057,0.5224 ± 0.0076,"{'classifier__n_neighbors': 3, 'classifier__weights': 'u..."
7,ReliefF,Decision Tree,0.8662 ± 0.0043,0.5285 ± 0.0051,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,0.8651 ± 0.0103,0.5107 ± 0.0393,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.8537 ± 0.0013,0.2846 ± 0.0308,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 4/10 ...     SVM: 1.0s
    kNN: 0.8s
    Decision Tree: 0.6s
    Random Forest: 4.7s
    MLP: 3.1s
    Starting ReliefF... done (0.8s)
    best_k selected: 10
    SVM: 0.6s
    kNN: 0.5s
    Decision Tree: 0.3s
    Random Forest: 4.1s
    MLP: 1.7s
done

  ── Fold 4/10 Results (Dataset4) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.8548 ± 0.0037,0.2805 ± 0.0121,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.8652 ± 0.0042,0.4993 ± 0.0119,"{'classifier__n_neighbors': 3, 'classifier__weights': 'u..."
2,Baseline,Decision Tree,0.8634 ± 0.0080,0.5022 ± 0.0269,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.8691 ± 0.0017,0.5165 ± 0.0029,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.8634 ± 0.0054,0.3688 ± 0.0718,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8548 ± 0.0027,0.2461 ± 0.0233,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.8691 ± 0.0049,0.5267 ± 0.0100,"{'classifier__n_neighbors': 3, 'classifier__weights': 'u..."
7,ReliefF,Decision Tree,0.8652 ± 0.0041,0.5206 ± 0.0145,"{'classifier__max_depth': None, 'classifier__min_samples..."
8,ReliefF,Random Forest,0.8660 ± 0.0090,0.5062 ± 0.0349,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.8545 ± 0.0018,0.2794 ± 0.0281,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 5/10 ...     SVM: 1.0s
    kNN: 0.8s
    Decision Tree: 0.6s
    Random Forest: 4.9s
    MLP: 2.7s
    Starting ReliefF... done (0.8s)
    best_k selected: 10
    SVM: 0.5s
    kNN: 0.6s
    Decision Tree: 0.3s
    Random Forest: 4.2s
    MLP: 1.6s
done

  ── Fold 5/10 Results (Dataset4) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.8548 ± 0.0033,0.2811 ± 0.0109,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.8638 ± 0.0047,0.5017 ± 0.0117,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.8648 ± 0.0077,0.5074 ± 0.0262,"{'classifier__max_depth': None, 'classifier__min_samples..."
3,Baseline,Random Forest,0.8681 ± 0.0024,0.5172 ± 0.0030,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.8619 ± 0.0057,0.3706 ± 0.0643,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8546 ± 0.0024,0.2444 ± 0.0212,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.8683 ± 0.0047,0.5289 ± 0.0100,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,0.8640 ± 0.0044,0.5159 ± 0.0160,"{'classifier__max_depth': None, 'classifier__min_samples..."
8,ReliefF,Random Forest,0.8658 ± 0.0081,0.5079 ± 0.0314,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.8550 ± 0.0019,0.2833 ± 0.0263,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 6/10 ...     SVM: 1.0s
    kNN: 0.8s
    Decision Tree: 0.6s
    Random Forest: 5.3s
    MLP: 3.3s
    Starting ReliefF... done (0.8s)
    best_k selected: 10
    SVM: 0.7s
    kNN: 0.6s
    Decision Tree: 0.3s
    Random Forest: 4.2s
    MLP: 2.2s
done

  ── Fold 6/10 Results (Dataset4) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.8550 ± 0.0031,0.2813 ± 0.0099,{'classifier__estimator__C': 1}
1,Baseline,kNN,0.8630 ± 0.0046,0.4939 ± 0.0205,"{'classifier__n_neighbors': 3, 'classifier__weights': 'u..."
2,Baseline,Decision Tree,0.8625 ± 0.0088,0.4989 ± 0.0305,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.8678 ± 0.0023,0.5104 ± 0.0155,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.8592 ± 0.0080,0.3650 ± 0.0601,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8545 ± 0.0023,0.2432 ± 0.0195,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.8684 ± 0.0042,0.5265 ± 0.0106,"{'classifier__n_neighbors': 3, 'classifier__weights': 'u..."
7,ReliefF,Decision Tree,0.8640 ± 0.0040,0.5114 ± 0.0177,"{'classifier__max_depth': None, 'classifier__min_samples..."
8,ReliefF,Random Forest,0.8649 ± 0.0077,0.5019 ± 0.0316,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.8546 ± 0.0019,0.2745 ± 0.0312,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."

  Fold 7/10 ...     SVM: 1.1s
    kNN: 0.8s
    Decision Tree: 0.6s
    Random Forest: 5.2s
    MLP: 2.7s
    Starting ReliefF... done (0.8s)
    best_k selected: 10
    SVM: 0.5s
    kNN: 0.5s
    Decision Tree: 0.3s
    Random Forest: 7.8s
    MLP: 2.3s
done

  ── Fold 7/10 Results (Dataset4) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.8541 ± 0.0036,0.2800 ± 0.0098,{'classifier__estimator__C': 1}
1,Baseline,kNN,0.8623 ± 0.0046,0.4878 ± 0.0241,"{'classifier__n_neighbors': 3, 'classifier__weights': 'u..."
2,Baseline,Decision Tree,0.8629 ± 0.0082,0.4951 ± 0.0298,"{'classifier__max_depth': None, 'classifier__min_samples..."
3,Baseline,Random Forest,0.8685 ± 0.0027,0.5066 ± 0.0171,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
4,Baseline,MLP,0.8571 ± 0.0090,0.3581 ± 0.0581,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."
5,ReliefF,SVM,0.8539 ± 0.0025,0.2413 ± 0.0186,{'classifier__estimator__C': 10}
6,ReliefF,kNN,0.8664 ± 0.0061,0.5203 ± 0.0182,"{'classifier__n_neighbors': 3, 'classifier__weights': 'u..."
7,ReliefF,Decision Tree,0.8626 ± 0.0051,0.5060 ± 0.0211,"{'classifier__max_depth': 20, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,0.8641 ± 0.0074,0.4970 ± 0.0316,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.8541 ± 0.0022,0.2839 ± 0.0370,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."

  Fold 8/10 ...     SVM: 1.0s
    kNN: 1.0s
    Decision Tree: 0.6s
    Random Forest: 7.5s
    MLP: 4.0s
    Starting ReliefF... done (0.9s)
    best_k selected: 10
    SVM: 0.7s
    kNN: 0.8s
    Decision Tree: 0.4s
    Random Forest: 6.3s
    MLP: 2.4s
done

  ── Fold 8/10 Results (Dataset4) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.8538 ± 0.0035,0.2793 ± 0.0093,{'classifier__estimator__C': 1}
1,Baseline,kNN,0.8633 ± 0.0051,0.4915 ± 0.0246,"{'classifier__n_neighbors': 3, 'classifier__weights': 'u..."
2,Baseline,Decision Tree,0.8637 ± 0.0080,0.4912 ± 0.0297,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.8688 ± 0.0026,0.5057 ± 0.0162,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
4,Baseline,MLP,0.8568 ± 0.0085,0.3639 ± 0.0564,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8537 ± 0.0024,0.2408 ± 0.0175,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.8670 ± 0.0059,0.5222 ± 0.0178,"{'classifier__n_neighbors': 3, 'classifier__weights': 'u..."
7,ReliefF,Decision Tree,0.8641 ± 0.0063,0.5105 ± 0.0231,"{'classifier__max_depth': None, 'classifier__min_samples..."
8,ReliefF,Random Forest,0.8655 ± 0.0079,0.5026 ± 0.0329,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.8539 ± 0.0021,0.2772 ± 0.0389,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 9/10 ...     SVM: 1.3s
    kNN: 1.0s
    Decision Tree: 0.7s
    Random Forest: 6.9s
    MLP: 3.5s
    Starting ReliefF... done (1.0s)
    best_k selected: 10
    SVM: 0.9s
    kNN: 0.7s
    Decision Tree: 0.4s
    Random Forest: 5.7s
    MLP: 2.5s
done

  ── Fold 9/10 Results (Dataset4) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.8532 ± 0.0036,0.2766 ± 0.0117,{'classifier__estimator__C': 1}
1,Baseline,kNN,0.8631 ± 0.0049,0.4897 ± 0.0237,"{'classifier__n_neighbors': 3, 'classifier__weights': 'u..."
2,Baseline,Decision Tree,0.8643 ± 0.0078,0.4933 ± 0.0286,"{'classifier__max_depth': None, 'classifier__min_samples..."
3,Baseline,Random Forest,0.8684 ± 0.0027,0.5051 ± 0.0153,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
4,Baseline,MLP,0.8584 ± 0.0092,0.3681 ± 0.0545,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."
5,ReliefF,SVM,0.8536 ± 0.0023,0.2396 ± 0.0168,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.8665 ± 0.0057,0.5188 ± 0.0193,"{'classifier__n_neighbors': 3, 'classifier__weights': 'u..."
7,ReliefF,Decision Tree,0.8639 ± 0.0059,0.5074 ± 0.0234,"{'classifier__max_depth': None, 'classifier__min_samples..."
8,ReliefF,Random Forest,0.8645 ± 0.0081,0.4991 ± 0.0326,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.8537 ± 0.0021,0.2735 ± 0.0381,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."

  Fold 10/10 ...     SVM: 1.3s
    kNN: 1.0s
    Decision Tree: 0.7s
    Random Forest: 6.9s
    MLP: 3.1s
    Starting ReliefF... done (1.0s)
    best_k selected: 10
    SVM: 0.7s
    kNN: 0.9s
    Decision Tree: 0.4s
    Random Forest: 6.6s
    MLP: 3.6s
done

  ── Fold 10/10 Results (Dataset4) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.8528 ± 0.0037,0.2771 ± 0.0111,{'classifier__estimator__C': 1}
1,Baseline,kNN,0.8625 ± 0.0050,0.4880 ± 0.0230,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.8636 ± 0.0077,0.4948 ± 0.0275,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.8681 ± 0.0027,0.5052 ± 0.0146,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.8583 ± 0.0088,0.3697 ± 0.0519,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8533 ± 0.0023,0.2387 ± 0.0162,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.8666 ± 0.0054,0.5223 ± 0.0211,"{'classifier__n_neighbors': 3, 'classifier__weights': 'u..."
7,ReliefF,Decision Tree,0.8641 ± 0.0057,0.5121 ± 0.0262,"{'classifier__max_depth': None, 'classifier__min_samples..."
8,ReliefF,Random Forest,0.8643 ± 0.0077,0.5009 ± 0.0314,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.8542 ± 0.0026,0.2798 ± 0.0408,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."

=== Dataset: Dataset5 ===
  Loaded: 9583 samples, 19 features, 4 classes
  Fold 1/10 ...     SVM: 4.2s
    kNN: 1.1s
    Decision Tree: 0.6s
    Random Forest: 7.1s
    MLP: 8.8s
    Starting ReliefF... done (1.0s)
    best_k selected: 10
    SVM: 1.4s
    kNN: 1.1s
    Decision Tree: 0.4s
    Random Forest: 5.6s
    MLP: 4.1s
done

  ── Fold 1/10 Results (Dataset5) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9708 ± 0.0000,0.9049 ± 0.0000,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9812 ± 0.0000,0.9429 ± 0.0000,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9979 ± 0.0000,0.9979 ± 0.0000,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9708 ± 0.0000,0.9094 ± 0.0000,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8342 ± 0.0000,0.6958 ± 0.0000,{'classifier__estimator__C': 10}
6,ReliefF,kNN,0.9896 ± 0.0000,0.9646 ± 0.0000,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9062 ± 0.0000,0.7890 ± 0.0000,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 2/10 ...     SVM: 4.6s
    kNN: 1.2s
    Decision Tree: 0.6s
    Random Forest: 6.3s
    MLP: 7.5s
    Starting ReliefF... done (0.9s)
    best_k selected: 10
    SVM: 0.8s
    kNN: 0.7s
    Decision Tree: 0.3s
    Random Forest: 4.8s
    MLP: 8.7s
done

  ── Fold 2/10 Results (Dataset5) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9724 ± 0.0016,0.9195 ± 0.0146,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9797 ± 0.0016,0.9419 ± 0.0011,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9990 ± 0.0010,0.9989 ± 0.0011,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9682 ± 0.0026,0.9126 ± 0.0032,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8452 ± 0.0109,0.6132 ± 0.0826,{'classifier__estimator__C': 10}
6,ReliefF,kNN,0.9818 ± 0.0078,0.8665 ± 0.0981,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.9301 ± 0.0240,0.7383 ± 0.0508,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."

  Fold 3/10 ...     SVM: 3.3s
    kNN: 1.1s
    Decision Tree: 0.6s
    Random Forest: 7.6s
    MLP: 7.4s
    Starting ReliefF... done (1.0s)
    best_k selected: 10
    SVM: 0.8s
    kNN: 0.8s
    Decision Tree: 0.3s
    Random Forest: 5.5s
    MLP: 4.4s
done

  ── Fold 3/10 Results (Dataset5) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9757 ± 0.0048,0.9401 ± 0.0315,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9823 ± 0.0039,0.9555 ± 0.0193,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9993 ± 0.0010,0.9993 ± 0.0010,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9722 ± 0.0060,0.9304 ± 0.0254,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8485 ± 0.0101,0.5936 ± 0.0729,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9809 ± 0.0065,0.8453 ± 0.0855,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.9214 ± 0.0231,0.6960 ± 0.0727,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 4/10 ...     SVM: 3.2s
    kNN: 1.1s
    Decision Tree: 0.6s
    Random Forest: 6.2s
    MLP: 7.0s
    Starting ReliefF... done (0.9s)
    best_k selected: 5
    SVM: 0.5s
    kNN: 0.4s
    Decision Tree: 0.2s
    Random Forest: 4.6s
    MLP: 2.3s
done

  ── Fold 4/10 Results (Dataset5) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9763 ± 0.0043,0.9469 ± 0.0298,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9825 ± 0.0034,0.9587 ± 0.0176,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9995 ± 0.0009,0.9995 ± 0.0009,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9739 ± 0.0060,0.9412 ± 0.0288,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8412 ± 0.0153,0.5015 ± 0.1716,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9844 ± 0.0082,0.8762 ± 0.0913,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9155 ± 0.0225,0.6711 ± 0.0764,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 5/10 ...     SVM: 4.1s
    kNN: 0.9s
    Decision Tree: 0.6s
    Random Forest: 6.0s
    MLP: 4.7s
    Starting ReliefF... done (0.9s)
    best_k selected: 5
    SVM: 0.4s
    kNN: 0.3s
    Decision Tree: 0.3s
    Random Forest: 4.7s
    MLP: 6.4s
done

  ── Fold 5/10 Results (Dataset5) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9783 ± 0.0056,0.9538 ± 0.0300,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9829 ± 0.0031,0.9611 ± 0.0165,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9996 ± 0.0008,0.9996 ± 0.0008,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9735 ± 0.0055,0.9427 ± 0.0259,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8393 ± 0.0142,0.4890 ± 0.1555,{'classifier__estimator__C': 10}
6,ReliefF,kNN,0.9871 ± 0.0092,0.9005 ± 0.0951,"{'classifier__n_neighbors': 11, 'classifier__weights': '..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9251 ± 0.0278,0.6778 ± 0.0696,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 6/10 ...     SVM: 2.7s
    kNN: 1.6s
    Decision Tree: 0.6s
    Random Forest: 6.2s
    MLP: 7.5s
    Starting ReliefF... done (0.9s)
    best_k selected: 10
    SVM: 0.9s
    kNN: 0.8s
    Decision Tree: 0.4s
    Random Forest: 5.1s
    MLP: 4.5s
done

  ── Fold 6/10 Results (Dataset5) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9774 ± 0.0055,0.9566 ± 0.0281,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9824 ± 0.0030,0.9629 ± 0.0156,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9997 ± 0.0008,0.9996 ± 0.0008,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9720 ± 0.0060,0.9450 ± 0.0242,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8405 ± 0.0132,0.4970 ± 0.1430,{'classifier__estimator__C': 10}
6,ReliefF,kNN,0.9847 ± 0.0099,0.8699 ± 0.1106,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.9221 ± 0.0263,0.6694 ± 0.0662,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."

  Fold 7/10 ...     SVM: 3.2s
    kNN: 1.0s
    Decision Tree: 0.6s
    Random Forest: 5.2s
    MLP: 6.1s
    Starting ReliefF... done (0.8s)
    best_k selected: 5
    SVM: 0.5s
    kNN: 0.4s
    Decision Tree: 0.2s
    Random Forest: 4.3s
    MLP: 2.3s
done

  ── Fold 7/10 Results (Dataset5) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9781 ± 0.0054,0.9566 ± 0.0260,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9827 ± 0.0029,0.9648 ± 0.0151,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9996 ± 0.0008,0.9995 ± 0.0008,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9720 ± 0.0056,0.9440 ± 0.0225,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."
5,ReliefF,SVM,0.8375 ± 0.0143,0.4582 ± 0.1630,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9867 ± 0.0104,0.8883 ± 0.1119,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9213 ± 0.0244,0.6660 ± 0.0619,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 8/10 ...     SVM: 3.5s
    kNN: 1.0s
    Decision Tree: 0.5s
    Random Forest: 5.4s
    MLP: 6.5s
    Starting ReliefF... done (0.9s)
    best_k selected: 10
    SVM: 0.9s
    kNN: 0.8s
    Decision Tree: 0.3s
    Random Forest: 4.9s
    MLP: 6.2s
done

  ── Fold 8/10 Results (Dataset5) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9790 ± 0.0056,0.9571 ± 0.0243,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9827 ± 0.0027,0.9650 ± 0.0142,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.9999 ± 0.0003,0.9978 ± 0.0058,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9996 ± 0.0007,0.9996 ± 0.0007,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9733 ± 0.0062,0.9451 ± 0.0213,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8394 ± 0.0143,0.4691 ± 0.1552,{'classifier__estimator__C': 10}
6,ReliefF,kNN,0.9860 ± 0.0099,0.8746 ± 0.1108,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,0.9999 ± 0.0003,0.9978 ± 0.0058,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,0.9999 ± 0.0003,0.9978 ± 0.0058,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.9258 ± 0.0257,0.6704 ± 0.0590,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."

  Fold 9/10 ...     SVM: 3.2s
    kNN: 1.0s
    Decision Tree: 0.6s
    Random Forest: 5.4s
    MLP: 6.7s
    Starting ReliefF... done (0.9s)
    best_k selected: 5
    SVM: 0.6s
    kNN: 0.4s
    Decision Tree: 0.2s
    Random Forest: 6.2s
    MLP: 2.5s
done

  ── Fold 9/10 Results (Dataset5) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9801 ± 0.0060,0.9605 ± 0.0249,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9833 ± 0.0031,0.9666 ± 0.0141,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.9999 ± 0.0003,0.9980 ± 0.0055,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9997 ± 0.0007,0.9996 ± 0.0007,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9737 ± 0.0060,0.9476 ± 0.0212,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8372 ± 0.0149,0.4420 ± 0.1652,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9875 ± 0.0102,0.8884 ± 0.1115,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,0.9999 ± 0.0003,0.9980 ± 0.0055,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,0.9999 ± 0.0003,0.9980 ± 0.0055,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9242 ± 0.0247,0.6667 ± 0.0566,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 10/10 ...     SVM: 3.3s
    kNN: 1.2s
    Decision Tree: 0.7s
    Random Forest: 6.5s
    MLP: 7.4s
    Starting ReliefF... done (0.7s)
    best_k selected: 10
    SVM: 0.8s
    kNN: 0.6s
    Decision Tree: 0.3s
    Random Forest: 4.8s
    MLP: 10.0s
done

  ── Fold 10/10 Results (Dataset5) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9800 ± 0.0057,0.9618 ± 0.0240,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9833 ± 0.0030,0.9669 ± 0.0134,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.9999 ± 0.0003,0.9982 ± 0.0053,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9997 ± 0.0007,0.9997 ± 0.0007,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9739 ± 0.0057,0.9494 ± 0.0209,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."
5,ReliefF,SVM,0.8421 ± 0.0204,0.4581 ± 0.1640,{'classifier__estimator__C': 10}
6,ReliefF,kNN,0.9863 ± 0.0103,0.8725 ± 0.1161,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,0.9999 ± 0.0003,0.9982 ± 0.0053,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,0.9998 ± 0.0004,0.9965 ± 0.0070,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9261 ± 0.0241,0.6691 ± 0.0541,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."

=== Dataset: Dataset6 ===
  Loaded: 9583 samples, 19 features, 4 classes
  Fold 1/10 ...     SVM: 5.3s
    kNN: 1.1s
    Decision Tree: 0.7s
    Random Forest: 7.0s
    MLP: 7.7s
    Starting ReliefF... done (1.0s)
    best_k selected: 10
    SVM: 1.8s
    kNN: 1.1s
    Decision Tree: 0.6s
    Random Forest: 5.0s
    MLP: 3.5s
done

  ── Fold 1/10 Results (Dataset6) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9708 ± 0.0000,0.9049 ± 0.0000,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9812 ± 0.0000,0.9429 ± 0.0000,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9979 ± 0.0000,0.9979 ± 0.0000,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9708 ± 0.0000,0.9094 ± 0.0000,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8342 ± 0.0000,0.6958 ± 0.0000,{'classifier__estimator__C': 10}
6,ReliefF,kNN,0.9896 ± 0.0000,0.9646 ± 0.0000,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9062 ± 0.0000,0.7890 ± 0.0000,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 2/10 ...     SVM: 4.2s
    kNN: 1.2s
    Decision Tree: 0.7s
    Random Forest: 6.4s
    MLP: 8.3s
    Starting ReliefF... done (0.9s)
    best_k selected: 10
    SVM: 1.0s
    kNN: 0.8s
    Decision Tree: 0.4s
    Random Forest: 5.2s
    MLP: 8.8s
done

  ── Fold 2/10 Results (Dataset6) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9724 ± 0.0016,0.9195 ± 0.0146,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9797 ± 0.0016,0.9419 ± 0.0011,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9990 ± 0.0010,0.9989 ± 0.0011,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9682 ± 0.0026,0.9126 ± 0.0032,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8452 ± 0.0109,0.6132 ± 0.0826,{'classifier__estimator__C': 10}
6,ReliefF,kNN,0.9818 ± 0.0078,0.8665 ± 0.0981,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.9301 ± 0.0240,0.7383 ± 0.0508,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."

  Fold 3/10 ...     SVM: 3.5s
    kNN: 1.2s
    Decision Tree: 0.6s
    Random Forest: 7.0s
    MLP: 7.5s
    Starting ReliefF... done (0.9s)
    best_k selected: 10
    SVM: 0.8s
    kNN: 0.7s
    Decision Tree: 0.3s
    Random Forest: 5.1s
    MLP: 3.9s
done

  ── Fold 3/10 Results (Dataset6) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9757 ± 0.0048,0.9401 ± 0.0315,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9823 ± 0.0039,0.9555 ± 0.0193,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9993 ± 0.0010,0.9993 ± 0.0010,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9722 ± 0.0060,0.9304 ± 0.0254,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8485 ± 0.0101,0.5936 ± 0.0729,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9809 ± 0.0065,0.8453 ± 0.0855,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.9214 ± 0.0231,0.6960 ± 0.0727,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 4/10 ...     SVM: 3.2s
    kNN: 0.8s
    Decision Tree: 0.5s
    Random Forest: 5.2s
    MLP: 6.3s
    Starting ReliefF... done (0.8s)
    best_k selected: 5
    SVM: 0.4s
    kNN: 0.4s
    Decision Tree: 0.2s
    Random Forest: 3.8s
    MLP: 1.5s
done

  ── Fold 4/10 Results (Dataset6) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9763 ± 0.0043,0.9469 ± 0.0298,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9825 ± 0.0034,0.9587 ± 0.0176,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9995 ± 0.0009,0.9995 ± 0.0009,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9739 ± 0.0060,0.9412 ± 0.0288,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8412 ± 0.0153,0.5015 ± 0.1716,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9844 ± 0.0082,0.8762 ± 0.0913,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9155 ± 0.0225,0.6711 ± 0.0764,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 5/10 ...     SVM: 3.3s
    kNN: 1.0s
    Decision Tree: 0.6s
    Random Forest: 5.8s
    MLP: 6.1s
    Starting ReliefF... done (1.0s)
    best_k selected: 5
    SVM: 0.5s
    kNN: 0.6s
    Decision Tree: 1.9s
    Random Forest: 6.1s
    MLP: 13.2s
done

  ── Fold 5/10 Results (Dataset6) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9783 ± 0.0056,0.9538 ± 0.0300,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9829 ± 0.0031,0.9611 ± 0.0165,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9996 ± 0.0008,0.9996 ± 0.0008,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9735 ± 0.0055,0.9427 ± 0.0259,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8393 ± 0.0142,0.4890 ± 0.1555,{'classifier__estimator__C': 10}
6,ReliefF,kNN,0.9871 ± 0.0092,0.9005 ± 0.0951,"{'classifier__n_neighbors': 11, 'classifier__weights': '..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9251 ± 0.0278,0.6778 ± 0.0696,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 6/10 ...     SVM: 12.1s
    kNN: 1.3s
    Decision Tree: 0.5s
    Random Forest: 7.2s
    MLP: 7.7s
    Starting ReliefF... done (1.1s)
    best_k selected: 10
    SVM: 0.9s
    kNN: 1.0s
    Decision Tree: 0.3s
    Random Forest: 5.1s
    MLP: 5.5s
done

  ── Fold 6/10 Results (Dataset6) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9774 ± 0.0055,0.9566 ± 0.0281,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9824 ± 0.0030,0.9629 ± 0.0156,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9997 ± 0.0008,0.9996 ± 0.0008,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9720 ± 0.0060,0.9450 ± 0.0242,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8405 ± 0.0132,0.4970 ± 0.1430,{'classifier__estimator__C': 10}
6,ReliefF,kNN,0.9847 ± 0.0099,0.8699 ± 0.1106,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.9221 ± 0.0263,0.6694 ± 0.0662,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."

  Fold 7/10 ...     SVM: 3.2s
    kNN: 2.6s
    Decision Tree: 3.7s
    Random Forest: 10.6s
    MLP: 8.9s
    Starting ReliefF... done (1.0s)
    best_k selected: 5
    SVM: 0.7s
    kNN: 0.5s
    Decision Tree: 0.2s
    Random Forest: 5.8s
    MLP: 2.4s
done

  ── Fold 7/10 Results (Dataset6) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9781 ± 0.0054,0.9566 ± 0.0260,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9827 ± 0.0029,0.9648 ± 0.0151,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9996 ± 0.0008,0.9995 ± 0.0008,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9720 ± 0.0056,0.9440 ± 0.0225,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."
5,ReliefF,SVM,0.8375 ± 0.0143,0.4582 ± 0.1630,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9867 ± 0.0104,0.8883 ± 0.1119,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9213 ± 0.0244,0.6660 ± 0.0619,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 8/10 ...     SVM: 4.1s
    kNN: 1.2s
    Decision Tree: 0.7s
    Random Forest: 7.5s
    MLP: 7.7s
    Starting ReliefF... done (1.0s)
    best_k selected: 10
    SVM: 1.4s
    kNN: 1.2s
    Decision Tree: 1.1s
    Random Forest: 7.2s
    MLP: 8.1s
done

  ── Fold 8/10 Results (Dataset6) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9790 ± 0.0056,0.9571 ± 0.0243,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9827 ± 0.0027,0.9650 ± 0.0142,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.9999 ± 0.0003,0.9978 ± 0.0058,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9996 ± 0.0007,0.9996 ± 0.0007,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9733 ± 0.0062,0.9451 ± 0.0213,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8394 ± 0.0143,0.4691 ± 0.1552,{'classifier__estimator__C': 10}
6,ReliefF,kNN,0.9860 ± 0.0099,0.8746 ± 0.1108,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,0.9999 ± 0.0003,0.9978 ± 0.0058,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,0.9999 ± 0.0003,0.9978 ± 0.0058,"{'classifier__max_depth': None, 'classifier__n_estimator..."
9,ReliefF,MLP,0.9258 ± 0.0257,0.6704 ± 0.0590,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."

  Fold 9/10 ...     SVM: 5.7s
    kNN: 1.5s
    Decision Tree: 0.9s
    Random Forest: 7.9s
    MLP: 8.5s
    Starting ReliefF... done (1.3s)
    best_k selected: 5
    SVM: 0.8s
    kNN: 0.6s
    Decision Tree: 0.4s
    Random Forest: 5.2s
    MLP: 2.4s
done

  ── Fold 9/10 Results (Dataset6) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9801 ± 0.0060,0.9605 ± 0.0249,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9833 ± 0.0031,0.9666 ± 0.0141,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.9999 ± 0.0003,0.9980 ± 0.0055,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9997 ± 0.0007,0.9996 ± 0.0007,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9737 ± 0.0060,0.9476 ± 0.0212,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8372 ± 0.0149,0.4420 ± 0.1652,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9875 ± 0.0102,0.8884 ± 0.1115,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,0.9999 ± 0.0003,0.9980 ± 0.0055,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,0.9999 ± 0.0003,0.9980 ± 0.0055,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9242 ± 0.0247,0.6667 ± 0.0566,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 10/10 ...     SVM: 3.0s
    kNN: 1.1s
    Decision Tree: 0.6s
    Random Forest: 6.5s
    MLP: 10.8s
    Starting ReliefF... done (0.8s)
    best_k selected: 10
    SVM: 1.0s
    kNN: 0.8s
    Decision Tree: 0.4s
    Random Forest: 7.1s
    MLP: 8.9s
done

  ── Fold 10/10 Results (Dataset6) | best_k=10 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9800 ± 0.0057,0.9618 ± 0.0240,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9833 ± 0.0030,0.9669 ± 0.0134,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,0.9999 ± 0.0003,0.9982 ± 0.0053,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9997 ± 0.0007,0.9997 ± 0.0007,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9739 ± 0.0057,0.9494 ± 0.0209,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."
5,ReliefF,SVM,0.8421 ± 0.0204,0.4581 ± 0.1640,{'classifier__estimator__C': 10}
6,ReliefF,kNN,0.9863 ± 0.0103,0.8725 ± 0.1161,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,0.9999 ± 0.0003,0.9982 ± 0.0053,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,0.9998 ± 0.0004,0.9965 ± 0.0070,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9261 ± 0.0241,0.6691 ± 0.0541,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."

=== Dataset: Dataset7 ===
  Loaded: 9583 samples, 19 features, 4 classes
  Fold 1/10 ...     SVM: 2.1s
    kNN: 1.7s
    Decision Tree: 0.8s
    Random Forest: 7.4s
    MLP: 8.2s
    Starting ReliefF... done (0.9s)
    best_k selected: 5
    SVM: 0.5s
    kNN: 0.4s
    Decision Tree: 0.2s
    Random Forest: 4.8s
    MLP: 2.1s
done

  ── Fold 1/10 Results (Dataset7) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9844 ± 0.0000,0.7351 ± 0.0000,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9791 ± 0.0000,0.7182 ± 0.0000,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9990 ± 0.0000,0.9990 ± 0.0000,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9698 ± 0.0000,0.7040 ± 0.0000,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8196 ± 0.0000,0.2253 ± 0.0000,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9969 ± 0.0000,0.9969 ± 0.0000,"{'classifier__n_neighbors': 21, 'classifier__weights': '..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9228 ± 0.0000,0.6562 ± 0.0000,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 2/10 ...     SVM: 1.6s
    kNN: 1.2s
    Decision Tree: 0.6s
    Random Forest: 6.0s
    MLP: 7.3s
    Starting ReliefF... done (0.8s)
    best_k selected: 5
    SVM: 0.5s
    kNN: 0.4s
    Decision Tree: 0.2s
    Random Forest: 5.2s
    MLP: 1.9s
done

  ── Fold 2/10 Results (Dataset7) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9781 ± 0.0063,0.7241 ± 0.0110,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9823 ± 0.0031,0.7231 ± 0.0049,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9995 ± 0.0005,0.9995 ± 0.0005,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9692 ± 0.0005,0.7049 ± 0.0009,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8196 ± 0.0000,0.2253 ± 0.0000,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9974 ± 0.0005,0.9975 ± 0.0005,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9145 ± 0.0083,0.6386 ± 0.0176,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 3/10 ...     SVM: 1.6s
    kNN: 1.2s
    Decision Tree: 0.6s
    Random Forest: 6.6s
    MLP: 7.3s
    Starting ReliefF... done (1.1s)
    best_k selected: 5
    SVM: 0.8s
    kNN: 0.5s
    Decision Tree: 0.3s
    Random Forest: 5.4s
    MLP: 3.1s
done

  ── Fold 3/10 Results (Dataset7) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9795 ± 0.0055,0.7257 ± 0.0093,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9840 ± 0.0035,0.7241 ± 0.0042,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9997 ± 0.0005,0.9997 ± 0.0005,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9712 ± 0.0027,0.7088 ± 0.0056,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8193 ± 0.0005,0.2253 ± 0.0001,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9979 ± 0.0009,0.9980 ± 0.0008,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9152 ± 0.0069,0.6376 ± 0.0144,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 4/10 ...     SVM: 1.8s
    kNN: 1.1s
    Decision Tree: 0.7s
    Random Forest: 6.8s
    MLP: 10.6s
    Starting ReliefF... done (0.9s)
    best_k selected: 5
    SVM: 0.6s
    kNN: 0.5s
    Decision Tree: 0.3s
    Random Forest: 6.8s
    MLP: 2.6s
done

  ── Fold 4/10 Results (Dataset7) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9799 ± 0.0048,0.7836 ± 0.1005,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9846 ± 0.0032,0.7858 ± 0.1071,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9997 ± 0.0005,0.9997 ± 0.0004,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9750 ± 0.0070,0.7727 ± 0.1107,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8193 ± 0.0004,0.2440 ± 0.0325,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9982 ± 0.0009,0.9981 ± 0.0008,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9160 ± 0.0061,0.6932 ± 0.0972,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 5/10 ...     SVM: 1.8s
    kNN: 1.2s
    Decision Tree: 0.7s
    Random Forest: 6.4s
    MLP: 7.7s
    Starting ReliefF... done (1.5s)
    best_k selected: 5
    SVM: 0.7s
    kNN: 0.4s
    Decision Tree: 0.3s
    Random Forest: 5.0s
    MLP: 2.6s
done

  ── Fold 5/10 Results (Dataset7) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9802 ± 0.0043,0.8218 ± 0.1180,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9846 ± 0.0029,0.8233 ± 0.1216,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9998 ± 0.0004,0.9998 ± 0.0004,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9756 ± 0.0064,0.8111 ± 0.1254,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."
5,ReliefF,SVM,0.8193 ± 0.0004,0.2553 ± 0.0367,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9977 ± 0.0012,0.9975 ± 0.0016,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9159 ± 0.0055,0.7253 ± 0.1080,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 6/10 ...     SVM: 1.8s
    kNN: 1.2s
    Decision Tree: 0.6s
    Random Forest: 8.3s
    MLP: 8.2s
    Starting ReliefF... done (0.8s)
    best_k selected: 5
    SVM: 0.5s
    kNN: 0.4s
    Decision Tree: 0.2s
    Random Forest: 5.3s
    MLP: 2.3s
done

  ── Fold 6/10 Results (Dataset7) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9800 ± 0.0040,0.8064 ± 0.1131,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9837 ± 0.0033,0.8051 ± 0.1182,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9997 ± 0.0005,0.9997 ± 0.0005,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9744 ± 0.0064,0.7951 ± 0.1199,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."
5,ReliefF,SVM,0.8193 ± 0.0004,0.2503 ± 0.0353,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9981 ± 0.0014,0.9979 ± 0.0017,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9157 ± 0.0050,0.7110 ± 0.1036,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 7/10 ...     SVM: 1.8s
    kNN: 1.2s
    Decision Tree: 0.7s

/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/home/sudhishp/Desktop/CS6735_final_project/.venv/lib/python3.12/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(

    Random Forest: 7.6s
    MLP: 8.2s
    Starting ReliefF... done (0.8s)
    best_k selected: 5
    SVM: 0.6s
    kNN: 0.5s
    Decision Tree: 0.3s
    Random Forest: 4.7s
    MLP: 2.8s
done

  ── Fold 7/10 Results (Dataset7) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9803 ± 0.0038,0.7953 ± 0.1082,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9845 ± 0.0037,0.8309 ± 0.1264,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9997 ± 0.0005,0.9997 ± 0.0005,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9751 ± 0.0061,0.7851 ± 0.1137,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8193 ± 0.0003,0.2467 ± 0.0339,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9981 ± 0.0013,0.9979 ± 0.0016,"{'classifier__n_neighbors': 21, 'classifier__weights': '..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9135 ± 0.0070,0.6969 ± 0.1020,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 8/10 ...     SVM: 1.4s
    kNN: 1.0s
    Decision Tree: 0.5s
    Random Forest: 6.7s
    MLP: 7.6s
    Starting ReliefF... done (0.7s)
    best_k selected: 5
    SVM: 0.6s
    kNN: 0.4s
    Decision Tree: 0.2s
    Random Forest: 4.1s
    MLP: 2.1s
done

  ── Fold 8/10 Results (Dataset7) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9804 ± 0.0035,0.7874 ± 0.1033,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9855 ± 0.0044,0.8194 ± 0.1221,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9997 ± 0.0005,0.9997 ± 0.0004,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9761 ± 0.0063,0.8093 ± 0.1241,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8194 ± 0.0003,0.2440 ± 0.0325,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9982 ± 0.0013,0.9980 ± 0.0015,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9126 ± 0.0070,0.6875 ± 0.0986,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 9/10 ...     SVM: 1.3s
    kNN: 1.0s
    Decision Tree: 0.5s
    Random Forest: 5.3s
    MLP: 7.9s
    Starting ReliefF... done (0.8s)
    best_k selected: 5
    SVM: 0.5s
    kNN: 0.4s
    Decision Tree: 0.2s
    Random Forest: 5.2s
    MLP: 2.2s
done

  ── Fold 9/10 Results (Dataset7) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9798 ± 0.0037,0.7800 ± 0.0996,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9854 ± 0.0042,0.8091 ± 0.1187,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9997 ± 0.0005,0.9997 ± 0.0005,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9762 ± 0.0060,0.7988 ± 0.1208,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."
5,ReliefF,SVM,0.8194 ± 0.0003,0.2420 ± 0.0312,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9984 ± 0.0013,0.9983 ± 0.0016,"{'classifier__n_neighbors': 11, 'classifier__weights': '..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9137 ± 0.0073,0.6841 ± 0.0935,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 10/10 ...     SVM: 1.4s
    kNN: 1.0s
    Decision Tree: 0.5s
    Random Forest: 5.8s
    MLP: 7.9s
    Starting ReliefF... done (0.8s)
    best_k selected: 5
    SVM: 0.6s
    kNN: 0.4s
    Decision Tree: 0.2s
    Random Forest: 4.3s
    MLP: 5.9s
done

  ── Fold 10/10 Results (Dataset7) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9792 ± 0.0040,0.7744 ± 0.0960,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9848 ± 0.0044,0.8257 ± 0.1232,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9997 ± 0.0005,0.9997 ± 0.0005,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9758 ± 0.0058,0.8156 ± 0.1251,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8229 ± 0.0107,0.2662 ± 0.0784,{'classifier__estimator__C': 10}
6,ReliefF,kNN,0.9980 ± 0.0016,0.9975 ± 0.0028,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9198 ± 0.0193,0.6876 ± 0.0893,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."

=== Dataset: Dataset8 ===
  Loaded: 9583 samples, 19 features, 4 classes
  Fold 1/10 ...     SVM: 1.5s
    kNN: 1.1s
    Decision Tree: 0.7s
    Random Forest: 5.9s
    MLP: 8.1s
    Starting ReliefF... done (0.9s)
    best_k selected: 5
    SVM: 0.5s
    kNN: 0.3s
    Decision Tree: 0.2s
    Random Forest: 4.6s
    MLP: 2.2s
done

  ── Fold 1/10 Results (Dataset8) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9844 ± 0.0000,0.7351 ± 0.0000,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9791 ± 0.0000,0.7182 ± 0.0000,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9990 ± 0.0000,0.9990 ± 0.0000,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9698 ± 0.0000,0.7040 ± 0.0000,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8196 ± 0.0000,0.2253 ± 0.0000,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9969 ± 0.0000,0.9969 ± 0.0000,"{'classifier__n_neighbors': 21, 'classifier__weights': '..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9228 ± 0.0000,0.6562 ± 0.0000,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 2/10 ...     SVM: 1.6s
    kNN: 1.2s
    Decision Tree: 0.5s
    Random Forest: 5.6s
    MLP: 7.7s
    Starting ReliefF... done (0.8s)
    best_k selected: 5
    SVM: 0.5s
    kNN: 0.4s
    Decision Tree: 0.2s
    Random Forest: 5.0s
    MLP: 2.4s
done

  ── Fold 2/10 Results (Dataset8) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9781 ± 0.0063,0.7241 ± 0.0110,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9823 ± 0.0031,0.7231 ± 0.0049,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9995 ± 0.0005,0.9995 ± 0.0005,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9692 ± 0.0005,0.7049 ± 0.0009,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8196 ± 0.0000,0.2253 ± 0.0000,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9974 ± 0.0005,0.9975 ± 0.0005,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9145 ± 0.0083,0.6386 ± 0.0176,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 3/10 ...     SVM: 1.5s
    kNN: 1.1s
    Decision Tree: 0.7s
    Random Forest: 6.7s
    MLP: 6.0s
    Starting ReliefF... done (0.7s)
    best_k selected: 5
    SVM: 1.5s
    kNN: 0.5s
    Decision Tree: 0.2s
    Random Forest: 4.8s
    MLP: 2.7s
done

  ── Fold 3/10 Results (Dataset8) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9795 ± 0.0055,0.7257 ± 0.0093,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9840 ± 0.0035,0.7241 ± 0.0042,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9997 ± 0.0005,0.9997 ± 0.0005,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9712 ± 0.0027,0.7088 ± 0.0056,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8193 ± 0.0005,0.2253 ± 0.0001,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9979 ± 0.0009,0.9980 ± 0.0008,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9152 ± 0.0069,0.6376 ± 0.0144,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 4/10 ...     SVM: 2.2s
    kNN: 1.4s
    Decision Tree: 0.7s
    Random Forest: 8.5s
    MLP: 9.7s
    Starting ReliefF... done (1.0s)
    best_k selected: 5
    SVM: 0.5s
    kNN: 0.3s
    Decision Tree: 0.2s
    Random Forest: 3.5s
    MLP: 1.6s
done

  ── Fold 4/10 Results (Dataset8) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9799 ± 0.0048,0.7836 ± 0.1005,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9846 ± 0.0032,0.7858 ± 0.1071,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9997 ± 0.0005,0.9997 ± 0.0004,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9750 ± 0.0070,0.7727 ± 0.1107,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8193 ± 0.0004,0.2440 ± 0.0325,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9982 ± 0.0009,0.9981 ± 0.0008,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9160 ± 0.0061,0.6932 ± 0.0972,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 5/10 ...     SVM: 1.2s
    kNN: 1.0s
    Decision Tree: 0.5s
    Random Forest: 4.6s
    MLP: 5.4s
    Starting ReliefF... done (0.8s)
    best_k selected: 5
    SVM: 0.6s
    kNN: 0.3s
    Decision Tree: 0.2s
    Random Forest: 3.9s
    MLP: 2.1s
done

  ── Fold 5/10 Results (Dataset8) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9802 ± 0.0043,0.8218 ± 0.1180,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9846 ± 0.0029,0.8233 ± 0.1216,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9998 ± 0.0004,0.9998 ± 0.0004,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9756 ± 0.0064,0.8111 ± 0.1254,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."
5,ReliefF,SVM,0.8193 ± 0.0004,0.2553 ± 0.0367,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9977 ± 0.0012,0.9975 ± 0.0016,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9159 ± 0.0055,0.7253 ± 0.1080,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 6/10 ...     SVM: 1.3s
    kNN: 1.1s
    Decision Tree: 0.7s
    Random Forest: 7.6s
    MLP: 8.6s
    Starting ReliefF... done (1.2s)
    best_k selected: 5
    SVM: 0.5s
    kNN: 0.4s
    Decision Tree: 0.2s
    Random Forest: 4.3s
    MLP: 1.9s
done

  ── Fold 6/10 Results (Dataset8) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9800 ± 0.0040,0.8064 ± 0.1131,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9837 ± 0.0033,0.8051 ± 0.1182,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9997 ± 0.0005,0.9997 ± 0.0005,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9744 ± 0.0064,0.7951 ± 0.1199,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."
5,ReliefF,SVM,0.8193 ± 0.0004,0.2503 ± 0.0353,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9981 ± 0.0014,0.9979 ± 0.0017,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9157 ± 0.0050,0.7110 ± 0.1036,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 7/10 ...     SVM: 1.4s
    kNN: 0.8s
    Decision Tree: 0.6s
    Random Forest: 5.8s
    MLP: 7.3s
    Starting ReliefF... done (0.8s)
    best_k selected: 5
    SVM: 0.5s
    kNN: 0.4s
    Decision Tree: 0.2s
    Random Forest: 4.5s
    MLP: 2.2s
done

  ── Fold 7/10 Results (Dataset8) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9803 ± 0.0038,0.7953 ± 0.1082,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9845 ± 0.0037,0.8309 ± 0.1264,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9997 ± 0.0005,0.9997 ± 0.0005,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9751 ± 0.0061,0.7851 ± 0.1137,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8193 ± 0.0003,0.2467 ± 0.0339,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9981 ± 0.0013,0.9979 ± 0.0016,"{'classifier__n_neighbors': 21, 'classifier__weights': '..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9135 ± 0.0070,0.6969 ± 0.1020,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 8/10 ...     SVM: 1.5s
    kNN: 1.0s
    Decision Tree: 0.6s
    Random Forest: 5.9s
    MLP: 7.3s
    Starting ReliefF... done (0.7s)
    best_k selected: 5
    SVM: 0.5s
    kNN: 0.3s
    Decision Tree: 0.2s
    Random Forest: 4.3s
    MLP: 2.0s
done

  ── Fold 8/10 Results (Dataset8) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9804 ± 0.0035,0.7874 ± 0.1033,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9855 ± 0.0044,0.8194 ± 0.1221,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9997 ± 0.0005,0.9997 ± 0.0004,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9761 ± 0.0063,0.8093 ± 0.1241,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8194 ± 0.0003,0.2440 ± 0.0325,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9982 ± 0.0013,0.9980 ± 0.0015,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9126 ± 0.0070,0.6875 ± 0.0986,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 9/10 ...     SVM: 1.4s
    kNN: 1.3s
    Decision Tree: 0.6s
    Random Forest: 5.9s
    MLP: 9.5s
    Starting ReliefF... done (0.8s)
    best_k selected: 5
    SVM: 0.5s
    kNN: 0.4s
    Decision Tree: 0.2s
    Random Forest: 20.4s
    MLP: 2.5s
done

  ── Fold 9/10 Results (Dataset8) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9798 ± 0.0037,0.7800 ± 0.0996,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9854 ± 0.0042,0.8091 ± 0.1187,"{'classifier__n_neighbors': 5, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9997 ± 0.0005,0.9997 ± 0.0005,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9762 ± 0.0060,0.7988 ± 0.1208,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."
5,ReliefF,SVM,0.8194 ± 0.0003,0.2420 ± 0.0312,{'classifier__estimator__C': 1}
6,ReliefF,kNN,0.9984 ± 0.0013,0.9983 ± 0.0016,"{'classifier__n_neighbors': 11, 'classifier__weights': '..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9137 ± 0.0073,0.6841 ± 0.0935,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."

  Fold 10/10 ...     SVM: 2.1s
    kNN: 1.1s
    Decision Tree: 0.6s
    Random Forest: 6.2s
    MLP: 8.7s
    Starting ReliefF... done (0.8s)
    best_k selected: 5
    SVM: 0.5s
    kNN: 0.4s
    Decision Tree: 0.2s
    Random Forest: 22.4s
    MLP: 5.6s
done

  ── Fold 10/10 Results (Dataset8) | best_k=5 ──

,Phase,Classifier,Accuracy,Macro-F1,Best Params
0,Baseline,SVM,0.9792 ± 0.0040,0.7744 ± 0.0960,{'classifier__estimator__C': 10}
1,Baseline,kNN,0.9848 ± 0.0044,0.8257 ± 0.1232,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
2,Baseline,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
3,Baseline,Random Forest,0.9997 ± 0.0005,0.9997 ± 0.0005,"{'classifier__max_depth': None, 'classifier__n_estimator..."
4,Baseline,MLP,0.9758 ± 0.0058,0.8156 ± 0.1251,"{'classifier__alpha': 0.0001, 'classifier__hidden_layer_..."
5,ReliefF,SVM,0.8229 ± 0.0107,0.2662 ± 0.0784,{'classifier__estimator__C': 10}
6,ReliefF,kNN,0.9980 ± 0.0016,0.9975 ± 0.0028,"{'classifier__n_neighbors': 3, 'classifier__weights': 'd..."
7,ReliefF,Decision Tree,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__min_samples_s..."
8,ReliefF,Random Forest,1.0000 ± 0.0000,1.0000 ± 0.0000,"{'classifier__max_depth': 10, 'classifier__n_estimators'..."
9,ReliefF,MLP,0.9198 ± 0.0193,0.6876 ± 0.0893,"{'classifier__alpha': 0.001, 'classifier__hidden_layer_s..."

  Checkpoint saved for Dataset8.